name: CI Workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "flights-429420"
  BUCKET_NAME: "flights-cicd-bucket"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install default-jdk -y
          pip install pytest pytest-cov pandas pyspark

      - name: Run tests
        run: python -m pytest --cov-report=html --cov=app .

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-history
          path: test_history

  create_zip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install zip
        run: sudo apt-get install zip

      - name: Create jobs.zip
        run: |
          cd app
          zip -r ../jobs.zip jobs

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: jobs
          path: jobs.zip


  google_cloud_services:
    runs-on: ubuntu-latest
    needs: create_zip
    steps:

      - uses: actions/checkout@v3

      - name: Download zip file artifact
        uses: actions/download-artifact@v3
        with:
          name: jobs
          path: ./downloads
      
      - name: Authenticate with GCP using Service Account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_ACCOUNT_KEY }}
      
      - name: Setup GCP CLI
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: 'gsutil'
      
      - name: Create GCS bucket if not exists
        run: |
          if ! gsutil ls -b gs://${{ env.BUCKET_NAME }}/; then
            gsutil mb -l EU gs://${{ env.BUCKET_NAME }}/
          fi
      
      - name: Upload files to GCS
        run: |
          gsutil cp ./downloads/jobs.zip gs://${{ env.BUCKET_NAME }}/jobs.zip
          gsutil cp app/main.py gs://${{ env.BUCKET_NAME }}/main.py
          gcloud storage objects update gs://${{ env.BUCKET_NAME }}/main.py --content-type=application/octet-stream


      - name: Submit Dataproc PySpark job
        run: |
          gcloud dataproc batches submit pyspark gs://$BUCKET_NAME/main.py \
            --project=$PROJECT_ID \
            --region=us-central1 \
            --batch=flights-batch-$(date +"%Y%m%d-%H%M%S") \
            --version=2.2 \
            --py-files=gs://$BUCKET_NAME/jobs.zip \
            --service-account=flights-service-acc-new@$PROJECT_ID.iam.gserviceaccount.com \
            --subnet=my-new-subnet
        env:
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
