name: CI Workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "flights-429420" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install default-jdk -y
          pip install pytest pytest-cov pandas pyspark

      - name: Run tests
        run: python -m pytest --cov-report=html --cov=app .

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-history
          path: test_history

  create_zip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install zip
        run: sudo apt-get install zip

      - name: Create jobs.zip
        run: |
          cd app
          zip -r ../jobs.zip jobs

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: jobs-zip
          path: jobs.zip

  google_cloud_services:
    runs-on: ubuntu-latest
    needs: create_zip
    steps:

      - uses: actions/checkout@v3

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@main
        with:
          project_id: "${{ secrets.GCP_PROJECT_ID }}"
          service_account_key: ${{ secrets.GCP_ACCOUNT_KEY }}

      - name: Authenticate GCP Account
        uses: 'google-github-actions/auth@v2'
        with:
           credentials_json: ${{ secrets.GCP_ACCOUNT_KEY }}
