name: CI Workflow

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "flights-429420" 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install default-jdk -y
          pip install pytest pytest-cov pandas pyspark

      - name: Run tests
        run: python -m pytest --cov-report=html --cov=app .

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-history
          path: test_history

  create_zip:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install zip
        run: sudo apt-get install zip

      - name: Create jobs.zip
        run: |
          cd app
          zip -r ../jobs.zip jobs

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: jobs-zip
          path: jobs.zip

  google_cloud_services:
    runs-on: ubuntu-latest
    needs: create_zip
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_ACCOUNT_KEY }}" > gcloud-service-key.json
          gcloud auth activate-service-account --key-file gcloud-service-key.json
          rm gcloud-service-key.json
          gcloud config set project "${{ env.PROJECT_ID }}"
